#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap -option caps:escape,shift:both_capslock &
xsetroot -cursor_name left_ptr &
picom -b &
nitrogen --restore &
~/.config/polybar/launch.sh &
pgrep bspswallow || bspswallow &
unclutter &

bspc monitor -d 1 2 3 4

bspc config border_width         2
bspc config window_gap          12
#bspc config top_padding 0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a rhubarb state=pseudo_tiled
